steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wearecity-puppeteer-service', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wearecity-puppeteer-service']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'wearecity-puppeteer-service'
    - '--image'
    - 'gcr.io/$PROJECT_ID/wearecity-puppeteer-service'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--timeout'
    - '300'
    - '--max-instances'
    - '10'
    - '--port'
    - '8080'

images:
  - 'gcr.io/$PROJECT_ID/wearecity-puppeteer-service'
